{
  "openapi": "3.0.0",
  "info": {
    "title": "team01-api-perpustakaan Express-rest API Swagger Documentation",
    "description": "The swagger doc for example perpustakaan api",
    "version": "1.0.0",
    "license": {
      "name": "ISC",
      "url": "https://spdx.org/licenses/ISC.html"
    },
    "contact": {
      "name": "team1-FSW1",
      "url": "https://github.com/RizqGyx/TEAM1-API-PERPUSTAKAAN"
    }
  },
  "tags": [
    {
      "name": "Auths",
      "description": "ini API untuk AUTHS resources"
    },
    {
      "name": "Users",
      "description": "ini API untuk USERS resources"
    },
    {
      "name": "Transactions",
      "description": "ini API untuk TRANSACTIONS resources"
    },
    {
      "name": "Books",
      "description": "ini API untuk BOOKS resources"
    },
    {
      "name": "Racks",
      "description": "ini API untuk RACKS resources"
    },
    {
      "name": "Libraries",
      "description": "ini API untuk LIBRARIES resources"
    }
  ],
  "servers": [
    {
      "url": "http://localhost:3000/api/v1"
    },
    {
      "url": "http://localhost:8000/api/v1"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "tags": ["Auths"],
        "summary": "Return hasil hit API login user",
        "description": "ini API utk login user",
        "requestBody": {
          "description": "ini request body utk sukses login user",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "rafi@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "rafi"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sukses Member login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "message": {
                      "type": "string",
                      "example": "Berhasil login"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "token": {
                          "type": "string",
                          "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJmYWRobGFuIiwicm9sZSI6IlN1cGVyYWRtaW4iLCJlbWFpbCI6ImZhZGhsYW5AZ21haWwuY29tIiwiaWF0IjoxNjk3OTM5ODMwfQ.hBED_9F3gLAwACOv7uOIeHR_6yKwQBwkf8WIVuEVQzs"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Email atau password tidak ada",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "email atau password harus diisi"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/register": {
      "post": {
        "tags": ["Auths"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return hasil hit API register member",
        "description": "ini API utk register member",
        "requestBody": {
          "description": "ini request body utk sukses register member",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "rahman"
                  },
                  "email": {
                    "type": "string",
                    "example": "rahman@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "rahman123"
                  },
                  "confirmPassword": {
                    "type": "string",
                    "example": "rahman123"
                  },
                  "age": {
                    "type": "integer",
                    "example": 20
                  },
                  "address": {
                    "type": "string",
                    "example": "Bekasi"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sukses register",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "dataValues": {
                          "id": 8,
                          "name": "rahman",
                          "address": "Bekasi",
                          "role": "Member",
                          "age": 20,
                          "updatedAt": "2023-10-22T02:04:31.713Z",
                          "createdAt": "2023-10-22T02:04:31.713Z"
                        },
                        "_previousDataValues": {
                          "name": "rahman",
                          "address": "Bekasi",
                          "role": "Member",
                          "age": 20,
                          "id": 8,
                          "createdAt": "2023-10-22T02:04:31.713Z",
                          "updatedAt": "2023-10-22T02:04:31.713Z"
                        },
                        "uniqno": 1,
                        "_changed": {},
                        "_options": {
                          "isNewRecord": true,
                          "_schema": null,
                          "_schemaDelimiter": ""
                        },
                        "isNewRecord": false,
                        "email": "rahman@gmail.com",
                        "password": "$2b$10$ycBSH81CDq.vzPrs6It74u5L4uDLF8Kfr6NHATFr8Cjeo5yUSAunC"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "tidak ada nama, email, atau password",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "nama, email, dan password harus diisi"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "email sudah terdaftar",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "email sudah terdaftar"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/me": {
      "get": {
        "tags": ["Auths"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return hasil hit API checktoken user",
        "description": "ini API utk checktoken user",
        "responses": {
          "200": {
            "description": "Sukses checktoken",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "id": 1,
                        "name": "fadhlan",
                        "age": 20,
                        "address": "Bogor",
                        "role": "Superadmin",
                        "email": "fadhlan@gmail.com"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Token tidak ada",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Tokennya tidak ada"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token tidak valid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Token tidak valid"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/create-admin": {
      "post": {
        "tags": ["Users"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return hasil hit API create user admin",
        "description": "ini API utk register admin",
        "requestBody": {
          "description": "ini request body utk sukses register member",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Ilyas"
                  },
                  "email": {
                    "type": "string",
                    "example": "ilyas@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "ilyas123"
                  },
                  "confirmPassword": {
                    "type": "string",
                    "example": "ilyas123"
                  },
                  "age": {
                    "type": "integer",
                    "example": 20
                  },
                  "address": {
                    "type": "string",
                    "example": "Bekasi"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sukses register",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "dataValues": {
                          "id": 9,
                          "name": "ilyas",
                          "address": "Bekasi",
                          "role": "Admin",
                          "age": 20,
                          "updatedAt": "2023-10-22T02:04:31.713Z",
                          "createdAt": "2023-10-22T02:04:31.713Z"
                        },
                        "_previousDataValues": {
                          "name": "Ilyas",
                          "address": "Bekasi",
                          "role": "Admin",
                          "age": 20,
                          "id": 9,
                          "createdAt": "2023-10-22T02:04:31.713Z",
                          "updatedAt": "2023-10-22T02:04:31.713Z"
                        },
                        "uniqno": 1,
                        "_changed": {},
                        "_options": {
                          "isNewRecord": true,
                          "_schema": null,
                          "_schemaDelimiter": ""
                        },
                        "isNewRecord": false,
                        "email": "ilyas@gmail.com",
                        "password": "$2b$10$ycBSH81CDq.vzPrs6It74u5L4uDLF8Kfr6NHATFr8Cjeo5yUSAunC"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "tidak ada nama, email, atau password",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "nama, email, dan password harus diisi"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token tidak valid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Token tidak valid"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Akses ditolak",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Kamu tidak berkepentingan disini"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "email sudah terdaftar",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "email sudah terdaftar"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": ["Users"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return hasil hit API get all users",
        "description": "ini API untuk mendapatkan semua data user",
        "responses": {
          "201": {
            "description": "Sukses mengambil semua data user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "users": [
                          {
                            "id": 1,
                            "name": "fadhlan",
                            "age": 20,
                            "address": "Bogor",
                            "role": "Superadmin",
                            "createdAt": "2023-10-21T05:45:15.380Z",
                            "updatedAt": "2023-10-21T05:45:15.380Z",
                            "Auth": {
                              "id": 1,
                              "email": "fadhlan@gmail.com",
                              "password": "$2a$10$w21UZzMLTtQBAem8xZYqQOjw4gfv/I4x61J3SuCtMZCpVM6p5E9TC",
                              "userId": 1,
                              "createdAt": "2023-10-21T05:45:15.389Z",
                              "updatedAt": "2023-10-21T05:45:15.389Z"
                            }
                          },
                          {
                            "id": 2,
                            "name": "Juki",
                            "age": 20,
                            "address": "Bekasi",
                            "role": "Superadmin",
                            "createdAt": "2023-10-21T05:45:15.380Z",
                            "updatedAt": "2023-10-21T05:45:15.380Z",
                            "Auth": {
                              "id": 2,
                              "email": "Juki@gmail.com",
                              "password": "$2a$10$M4V45l3wCRfrXkOBEchvOe6ymWBIsBaTdcKr/smXL7ChUJFescH5q",
                              "userId": 2,
                              "createdAt": "2023-10-21T05:45:15.389Z",
                              "updatedAt": "2023-10-21T05:45:15.389Z"
                            }
                          },
                          {
                            "id": 3,
                            "name": "Jose",
                            "age": 20,
                            "address": "Bekasi",
                            "role": "Superadmin",
                            "createdAt": "2023-10-21T05:45:15.380Z",
                            "updatedAt": "2023-10-21T08:26:43.619Z",
                            "Auth": {
                              "id": 3,
                              "email": "Jojo@gmail.com",
                              "password": "$2a$10$isuqDbs2rfTVxZkTE/Vp8.Tt0H/Hhjqpl8cQ6668obTzUWiZ8.5BK",
                              "userId": 3,
                              "createdAt": "2023-10-21T05:45:15.389Z",
                              "updatedAt": "2023-10-21T05:45:15.389Z"
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token tidak valid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Token tidak valid"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Akses ditolak",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Kamu tidak berkepentingan disini"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "tags": ["Users"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return hasil hit API get user by id",
        "description": "ini API untuk mendapatkan data user berdasarkan id ",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            },
            "description": "User ID"
          }
        ],
        "responses": {
          "201": {
            "description": "Sukses mendapatkan data user berdasarkan id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "users": {
                          "id": 1,
                          "name": "fadhlan",
                          "age": 20,
                          "address": "Bogor",
                          "role": "Superadmin",
                          "createdAt": "2023-10-21T05:45:15.380Z",
                          "updatedAt": "2023-10-21T05:45:15.380Z",
                          "Auth": {
                            "id": 1,
                            "email": "fadhlan@gmail.com",
                            "password": "$2a$10$w21UZzMLTtQBAem8xZYqQOjw4gfv/I4x61J3SuCtMZCpVM6p5E9TC",
                            "userId": 1,
                            "createdAt": "2023-10-21T05:45:15.389Z",
                            "updatedAt": "2023-10-21T05:45:15.389Z"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token tidak valid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Token tidak valid"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Akses ditolak",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Kamu tidak berkepentingan disini"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User tidak ada",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "User dengan id: 1 tidak ada"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/edit": {
      "patch": {
        "tags": ["Users"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return hasil hit API edit user by login",
        "description": "ini API untuk mengedit data user dengan login",
        "requestBody": {
          "description": "ini request body untuk edit user",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "jose"
                  },
                  "address": {
                    "type": "string",
                    "example": "jakarta"
                  },
                  "age": {
                    "type": "integer",
                    "example": 24
                  },
                  "email": {
                    "type": "string",
                    "example": "jose@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "josee123"
                  },
                  "confirmPassword": {
                    "type": "string",
                    "example": "josee123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sukses mengedit data user dengan login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "id": 1,
                        "name": "jose",
                        "age": 24,
                        "address": "Jakarta",
                        "role": "Superadmin",
                        "createdAt": "2023-10-22T07:53:51.986Z",
                        "updatedAt": "2023-10-22T08:23:37.388Z",
                        "Auth": {
                          "id": 1,
                          "email": "jose@gmail.com",
                          "password": "$2b$10$aR8/K7FhtNG6oW8gZfzM7OWvICjO98dEYqLhONTw2ZCwJogi49aIi",
                          "userId": 1,
                          "createdAt": "2023-10-22T07:53:51.996Z",
                          "updatedAt": "2023-10-22T08:23:37.395Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token tidak valid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Token tidak valid"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/edit/{id}": {
      "patch": {
        "tags": ["Users"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return hasil hit API edit user by id",
        "description": "ini API untuk mengedit data user berdasarkan id ",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            },
            "description": "User ID"
          }
        ],
        "requestBody": {
          "description": "ini request body untuk edit user",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "ridwan"
                  },
                  "address": {
                    "type": "string",
                    "example": "Bogor"
                  },
                  "age": {
                    "type": "integer",
                    "example": 25
                  },
                  "email": {
                    "type": "string",
                    "example": "ridwan@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "ridwan123"
                  },
                  "confirmPassword": {
                    "type": "string",
                    "example": "ridwan123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sukses mengedit data user berdasarkan id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "id": 3,
                        "name": "Ridwan",
                        "age": 25,
                        "address": "Bogor",
                        "role": "Superadmin",
                        "createdAt": "2023-10-22T07:53:51.986Z",
                        "updatedAt": "2023-10-22T08:23:37.388Z",
                        "Auth": {
                          "id": 3,
                          "email": "ridwan@gmail.com",
                          "password": "$2b$10$aR8/K7FhtNG6oW8gZfzM7OWvICjO98dEYqLhONTw2ZCwJogi49aIi",
                          "userId": 3,
                          "createdAt": "2023-10-22T07:53:51.996Z",
                          "updatedAt": "2023-10-22T08:23:37.395Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Token tidak valid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Token tidak valid"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Akses ditolak",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Kamu tidak berkepentingan disini"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User tidak ada",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "User dengan id: 1 tidak ada"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/delete/{id}": {
      "delete": {
        "tags": ["Users"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return hasil hit API delete user by id",
        "description": "ini API untuk menghapus data user berdasarkan id",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 1
            },
            "description": "User ID"
          }
        ],
        "responses": {
          "201": {
            "description": "Sukses menghapus data user berdasarkan id"
          },
          "401": {
            "description": "Token tidak valid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Token tidak valid"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Akses ditolak",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Kamu tidak berkepentingan disini"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User tidak ada",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "User dengan id: 6 tidak ada"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/book/{id}": {
      "get": {
        "tags": ["Books"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Get book by id",
        "description": "Use this API to GET book data by id ",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 2
            },
            "description": "Book ID"
          }
        ],
        "responses": {
          "201": {
            "description": "Success getting book data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                  "books": {
                          "id": 2,
                          "title": "To Kill a Mockingbird",
                          "genre": "Fiction",
                          "author": "Harper Lee",
                          "language": "English",
                          "publicationYear": 1960,
                          "publisher": "J. B. Lippincott & Co.",
                          "imageCover": "http://via.placeholder.com/600x400",
                          "numOfBooks": 8,
                          "numBorrowed": 1,
                          "rackId": 2,
                          "createdAt": "2023-06-29T07:30:00.000Z",
                          "updatedAt": "2023-06-29T07:30:00.000Z",
                          "Rack": {
                              "id": 2,
                              "rackNumber": 2,
                              "floorNumber": 1,
                              "libraryId": 2,
                              "createdAt": "2023-06-03T09:00:00.000Z",
                              "updatedAt": "2023-06-03T09:00:00.000Z"
                          }

                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                  "message": {
                          "type": "string",
                          "example": "Token not found"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Cant find book with requested id" ,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string",
                          "example": "Book not found"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Books"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Edit book data",
        "description": "Use this API to edit or update books data ",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 3
            },
            "description": "User ID"
          }
        ],
        "requestBody": {
          "description": "Request body",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "Servant of Evil"
                  },
                  "genre": {
                    "type": "string",
                    "example": "Fiction"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Sukses mengedit data user berdasarkan id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "id": 3,
                        "title": "Servant of Evil",
                        "genre": "Fiction",
                        "author": "George Orwell",
                        "language": "English",
                        "publicationYear": 1949,
                        "publisher": "Secker & Warburg",
                        "imageCover": "http://via.placeholder.com/600x400",
                        "numOfBooks": 6,
                        "numBorrowed": 0,
                        "rackId": 3,
                        "createdAt": "2023-06-30T10:45:00.000Z",
                        "updatedAt": "2024-04-20T19:54:03.297Z",
                        "Rack": {
                          "id": 3,
                          "rackNumber": 3,
                          "floorNumber": 2,
                          "libraryId": 3,
                          "createdAt": "2023-06-04T09:00:00.000Z",
                          "updatedAt": "2023-06-04T09:00:00.000Z"
                        } 
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                      "message": {
                      "type": "string",
                      "example": "Token not found"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Access denied",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                      "message": {
                      "type": "string",
                      "example": "You are not authorized. Required role Admin or Staff"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Cant find book with requested id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Book not found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Books"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Delete book data",
        "description": "Use this API to delete books ",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "example": 3
            },
            "description": "User ID"
          }
        ],
        "responses": {
          "201": {
            "description": "Success deleting book data",
            "content": {
              "application/json":{
                "schema":{
                "type": "object",
                "properties": {
                  "status":{
                    "type": "string",
                    "example": "Success"
                  },
                  "message":{
                    "type":"string",
                    "example": "Book has been deleted"
                  }
                }
              }
              }
            }
            
          },
          "401": {
            "description": "Invalid token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                      "message": {
                      "type": "string",
                      "example": "Token not found"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Access denied",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                      "message": {
                      "type": "string",
                      "example": "You are not authorized. Required role Admin or Staff"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Cant find book with requested id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Book not found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }, 
    "/book/": {
      "get": {
        "tags": ["Books"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Return book data that has been filtered",
        "description": "Use this API to do filtering",
        "parameters": [
          {
            "name": "search",
            "in": "path",
            "schema": {
              "type": "string",
              "example": "search=The Great Gatsby"
            },
            "description": "Seach param"
          },
          {
            "name": "genre",
            "in": "path",
            "schema": {
              "type": "string",
              "example": "genre=fiction"
            },
            "description": "shortby genre"
          },
          {
            "name": "author",
            "in": "path",
            "schema": {
              "type": "string",
              "example": "author=scott    "
            },
            "description": "shortby author"
          }
        ],
        "responses": {
          "201": {
            "description": "Success to get book data based on filter param",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "book": {
                      "type": "object",
                      "example": {
                        "id": 1,
                        "title": "The Great Gatsby",
                        "genre": "Fiction",
                        "author": "F. Scott Fitzgerald",
                        "language": "English",
                        "publicationYear": 1925,
                        "publisher": "Scribner",
                        "imageCover": "http://via.placeholder.com/600x400",
                        "numOfBooks": 10,
                        "numBorrowed": 2,
                        "rackId": 1,
                        "createdAt": "2023-06-28T09:25:00.000Z",
                        "updatedAt": "2023-06-28T09:25:00.000Z"
                      }
                    },
                    "data": {
                      "type": "object",
                      "example": {
                        "TotalData": 1,
                        "totalPages": 1,
                        "limit": 1
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                  "message": {
                          "type": "string",
                          "example": "Token not found"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Cant find book with requested id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                  "message": {
                          "type": "string",
                          "example": "Book not found"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Books"],
        "security": [
          {
            "bearerToken": []
          }
        ],
        "summary": "Create new book data",
        "description": "ini API utk register member",
        "requestBody": {
          "description": "Request body",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "arknight"
                  },
                  "author": {
                    "type": "string",
                    "example": "jhon doe"
                  },
                  "publisher": {
                    "type": "string",
                    "example": "Yostar"
                  },
                  "publicationYear": {
                    "type": "integer",
                    "example": 2020
                  },
                  "genre": {
                    "type": "integer",
                    "example": "action"
                  },
                  "numOfBooks": {
                    "type": "string",
                    "example": "3"
                  },
                  "numBorrowed": {
                    "type": "string",
                    "example": "0"
                  },
                  "rackId": {
                    "type": "string",
                    "example": "1"
                  },
                  "language": {
                    "type": "string",
                    "example": "English"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success adding new book",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Success"
                    },
                    "book": {
                      "type": "object",
                      "example": {
                        "imageCover": "https://dailymockup.com/wp-content/uploads/edd/2019/04/free-book-cover-mockup-psd.jpg",
                        "id": 11,
                        "title": "arknight",
                        "genre": "action",
                        "author": "jhon doe",
                        "language": "English",
                        "publicationYear": 2020,
                        "publisher": "Yostar",
                        "numOfBooks": 3,
                        "numBorrowed": 0,
                        "rackId": 1,
                        "updatedAt": "2024-04-20T18:33:03.010Z",
                        "createdAt": "2024-04-20T18:33:03.010Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "There is a field with null value  ",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                      "message": {
                        "type": "string",
                        "example": "Input cant be null"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid token",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Failed"
                    },
                      "message": {
                      "type": "string",
                      "example": "Token not found"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Access denied",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "Error"
                    },
                      "message": {
                      "type": "string",
                      "example": "You are not authorized. Required role Admin or Staff"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerToken": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}
